[build]
publish = "build"
command = "yarn build"

[[redirects]]
    from = "/"
    to = "/index.xhtml"
    status = 200

[[headers]]
    for = "/*"
[headers.values]
    Access-Control-Allow-Origin = "*"